services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice_management_prod_backend
    restart: always
    depends_on:
      - db_prod
    env_file:
      - .env.production
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${BACKEND_HOST_PORT:-3001}:3001"
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

  db_prod:
    image: mysql:8.4.4
    container_name: invoice_management_db_prod_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_prod_data:/var/lib/mysql
    env_file:
      - .env.production
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s 
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: invoice_management_db_prod_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  mysql_prod_data: